apiVersion: hawt.io/v1alpha1
kind: Hawtio
metadata:
  name: example-hawtio
spec:
  # the deployment type, either "cluster" or "namespace":
  # - cluster: Hawtio is capable of discovering and managing
  #   applications accross all namespaces the authenticated user
  #   has access to.
  # - namespace: Hawtio is capable of discovering and managing
  #   applications within the deployment namespace.
  type: namespace
  replicas: 1
  # routeHostName: hawtio.192.168.64.38.nip.io
