apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hawtios.hawt.io
spec:
  group: hawt.io
  names:
    kind: Hawtio
    listKind: HawtioList
    plural: hawtios
    singular: hawtio
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
    - name: Age
      description: Creation date
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: URL
      description: Hawtio console URL
      type: string
      JSONPath: .status.routeHostName
