apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - '*'
- apiGroups:
  - hawtio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - hawt.io
  resources:
  - '*'
  - hawtios
  verbs:
  - '*'
