apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - '*'
- apiGroups:
  - hawt.io
  resources:
  - '*'
  - hawtios
  verbs:
  - '*'
